const person_jake = [
    ["Title","Lat", "Long", "Text", "Bild"],
    ["01","47.27055472371641", "11.403663199182649",  "Since the start oft the pandemic it is not possible for me to go to my favorite coffee place and enjoy a hot pot a coffee. I really miss the possibility to make a break, change my surrounding setting. I noticed that being at home in my all in one room makes it harder for me to relax and get rid of the pressure to study. ", "r01.jpg"],
    ["02","47.25500340883769", "11.33476190115422",  "Due to the restrictions and the mantra of physical distancing I encounter new areas in my neighborhood. For example a possible path besides the river Inn. When you walk down there, you meet almost no one, even if the crowded footpath is less than 10 metres away. I walked this “path” for many miles with the challenge to stay as close to the river as possible. Even though the restrictions in the summer were much more lax than in the spring or today, I have maintained this routine. And I think I will maintain it post-pandemic as well. ", "r02.jpg"],
    ["03","47.25435262448998", "11.3722052771174",  "Allthough I really like my apartment I often feel constrained. As time goes by, I notice more and more how I take refuge in my studies. The longer this situation lasts and the longer I am stuck here with incredibly reduced social contacts, the harder it is for me to maintain any social contact at all. For me, it is much more exhausting to have social contacts from scratch in a digital setting than when they run into you or when you physically visit friends, family etc.  <br> One positive Aspect of the hard restrictions we had in March-April 2020 was that I reencountered my love to clean, and repair bicycles. This took up a huge amount of time, which my flatmates often acknowledged with astonishment - I, on the other hand, enjoyed it very much!", "r03.jpg"],
    ["04","47.25435262448998", "11.3722052771174", "One positive Aspect of the hard restrictions we had in March-April 2020 was that I reencountered my love to clean, and repair bicycles. This took up a huge amount of time, which my flatmates often acknowledged with astonishment - I, on the other hand, enjoyed it very much!", "r04.jpg"],
    ["05","47.26448344865574", "11.384799581601118", "For me, the biggest change is the closed university. By that I don't mean that I can no longer continue studying, quite the opposite. Distance learning makes it possible (under the circumstances) to continue taking and completing your modules. However, apart from the aspect of the university to take and complete the necessary modules, ALL other aspects are missing for me. It is difficult for me to describe the aspects I am referring to without oversimplifying them. For example the way to university, for me this is an essential aspect, it activates me physical but also initiates the start of the studying process. The same applies for entering the building, the lecture- / seminar rooms. OR the issue of chatting with your maids before and after the lectures. Its not only about chit-chat but mainly about engaging into to content reflecting about it and finding new ideas, perspectives, etc. . For me personally the whole dynamics of studying is frozen due to distance learning. In this setting studying is becoming more and more like the kind of education I find displeasing - frontal teaching dictated by the teacher. ",]

];
const person_rosa = [
    ["Title","Lat", "Long", "Text", "Bild"],
    ["01","47.284435341743624", "11.506330713414243",  "The first lockdown from march 2020 onwards was a quite challenging time. In the federal state of Tyrol where I live, people were literally locked-in their apartments. We could only leave our flats to do the most necessary errands. Except supermarkets and other shops of daily needs, everything was closed. How lucky I was when in the end of April 2020 restrictions were eased! I went to a garden centre and bought as many plants and herbs as possible to start a garden project on my tiny balcony – a place which became pretty important to me in the following months against the backdrop of travel restrictions and the fear of overcrowded places.", "c01.jpg"],
    ["01","47.271974833237465", "11.388832713413825", "Back in office! After at least 4 months of homeoffice the situation relaxed and my working collegues and I were able to go back to our office in Innsbruck. The photo was taken in the beginning of autumn 2020 when I realized how much I appreciate to have my own office with a fantastic view over the city. My office stands for having a place where ideas are born, where teamwork is done, but also for a place where I can leave work assignments and stress behind at the end of the day. No need to take it with me in my private rooms – something I really struggled to handle during times of lockdown and enacted homeoffice.", "c02.jpg"],
];

const person_santiago= [
    ["Title","Lat", "Long", "Text", "Bild"],
    ["01","47.26797038857142", "11.390618209779843", "This picture shows the promenade in the centre of Innsbruck. During the first lock down in spring 2020 I spent a lot of my time there, enjoying the sun and going for a walk. The weather was really good back then and it felt a little bit like holidays. However, it was a strange feeling, because all the shops were closed and the police controlled if people weren’t meeting each other illegally.", "wien_logo.png","l_01.jpg"]
];