const person_jake = [
    ["Title","Lat", "Long", "Text", "Bild"],
    ["Jake 01","47.27055472371641", "11.403663199182649",  "Since the start oft the pandemic it is not possible for me to go to my favorite coffee place and enjoy a hot pot a coffee. I really miss the possibility to make a break, change my surrounding setting. I noticed that being at home in my all in one room makes it harder for me to relax and get rid of the pressure to study. ", "r01.jpg"],
    ["Jake 02","47.25500340883769", "11.33476190115422",  "Due to the restrictions and the mantra of physical distancing I encounter new areas in my neighborhood. For example a possible path besides the river Inn. When you walk down there, you meet almost no one, even if the crowded footpath is less than 10 metres away. I walked this “path” for many miles with the challenge to stay as close to the river as possible. Even though the restrictions in the summer were much more lax than in the spring or today, I have maintained this routine. And I think I will maintain it post-pandemic as well. ", "r02.jpg"],
    ["Jake 03","47.25435262448998", "11.3722052771174",  "Allthough I really like my apartment I often feel constrained. As time goes by, I notice more and more how I take refuge in my studies. The longer this situation lasts and the longer I am stuck here with incredibly reduced social contacts, the harder it is for me to maintain any social contact at all. For me, it is much more exhausting to have social contacts from scratch in a digital setting than when they run into you or when you physically visit friends, family etc.  <br> One positive Aspect of the hard restrictions we had in March-April 2020 was that I reencountered my love to clean, and repair bicycles. This took up a huge amount of time, which my flatmates often acknowledged with astonishment - I, on the other hand, enjoyed it very much!", "r03.jpg"],
    ["Jake 04","47.25435262448998", "11.3722052771174", "One positive Aspect of the hard restrictions we had in March-April 2020 was that I reencountered my love to clean, and repair bicycles. This took up a huge amount of time, which my flatmates often acknowledged with astonishment - I, on the other hand, enjoyed it very much!", "r04.jpg"],
    ["Jake 05","47.26448344865574", "11.384799581601118", "For me, the biggest change is the closed university. By that I don't mean that I can no longer continue studying, quite the opposite. Distance learning makes it possible (under the circumstances) to continue taking and completing your modules. However, apart from the aspect of the university to take and complete the necessary modules, ALL other aspects are missing for me. It is difficult for me to describe the aspects I am referring to without oversimplifying them. For example the way to university, for me this is an essential aspect, it activates me physical but also initiates the start of the studying process. The same applies for entering the building, the lecture- / seminar rooms. OR the issue of chatting with your maids before and after the lectures. Its not only about chit-chat but mainly about engaging into to content reflecting about it and finding new ideas, perspectives, etc. . For me personally the whole dynamics of studying is frozen due to distance learning. In this setting studying is becoming more and more like the kind of education I find displeasing - frontal teaching dictated by the teacher. ",],




    ["Rosa 01","47.284435341743624", "11.506330713414243",  "The first lockdown from march 2020 onwards was a quite challenging time. In the federal state of Tyrol where I live, people were literally locked-in their apartments. We could only leave our flats to do the most necessary errands. Except supermarkets and other shops of daily needs, everything was closed. How lucky I was when in the end of April 2020 restrictions were eased! I went to a garden centre and bought as many plants and herbs as possible to start a garden project on my tiny balcony – a place which became pretty important to me in the following months against the backdrop of travel restrictions and the fear of overcrowded places.", "c01.jpg"],
    ["Rosa 02","47.271974833237465", "11.388832713413825", "Back in office! After at least 4 months of homeoffice the situation relaxed and my working collegues and I were able to go back to our office in Innsbruck. The photo was taken in the beginning of autumn 2020 when I realized how much I appreciate to have my own office with a fantastic view over the city. My office stands for having a place where ideas are born, where teamwork is done, but also for a place where I can leave work assignments and stress behind at the end of the day. No need to take it with me in my private rooms – something I really struggled to handle during times of lockdown and enacted homeoffice.", "c02.jpg"],


    ["Santiago 01","47.26797038857142", "11.390618209779843", "This picture shows the promenade in the centre of Innsbruck. During the first lock down in spring 2020 I spent a lot of my time there, enjoying the sun and going for a walk. The weather was really good back then and it felt a little bit like holidays. However, it was a strange feeling, because all the shops were closed and the police controlled if people weren’t meeting each other illegally.","l_01.jpg"],
    ["Santiago 02","47.26407154513746", "11.366084959170562", "This picture was taken on the balcony of the flat where I lived. During the first time of the pandemic, I spent a lot of my time there. I read books, did some tasks for university or just enjoyed the sun. The picture should also show that during the first lockdown my boyfriend and me had enough time to cook together.","l_02.jpg"],


    ["Emma 01 Homeoffice","47.25936317749856", "11.389755572632998", "I am working for a NGO with a lot of volunteers and I am usually coordinating events, it was very unusual to work at home and organize only online meetings and webinars. My dear colleagues all tried to do their best, but we also have some elderly people helping us with organizing event, so they were not used to work online. It took our team a few weeks and a few webinars to convince them. At the end they were very happy to learn a lot and at the moment we do also our internal workshops online. But this cannot replace personal contact. When you have to do all the work for your job and our studies remote the screen time sums up to more than 10 hours per day.","jb01.jpg"],
    ["Emma 02 Shopping panic","47.260898809757926", "11.391904512521293", "At the very beginning of the first lockdown a lot of people got panic and bought a lot of toilet paper. In a shop close to my apartment, they put a pack of toilet paper in the entrance area. There was a sign with the text: “No hamster shopping, please!” After a few weeks, people trusted the government and the supply chains again and didn’t by all the available toilet paper they could find in the shops. Another sold out product were pasta, tomato sauce and yeast, seemed like everyone is cooking pizza, pasta and baking bread.","jb02.jpg"],
    ["Emma 03 Flowers in the lockdown","47.25936317749856", "11.389755572632998", "Before the shops were closed I took the chance and got a lot of flowers for the balcony. I was very happy to have some feeling of spring and a few colours around me. I also like to the work of potting flowers and to do some work with my hands, not only working in front of my laptop. We also tried to grow some salad, tomatoes, cucumber and all kinds of herbs.","jb03.jpg"],
    ["Emma 04 A lot of cooking","47.25936317749856", "11.389755572632998", "All restaurants and hotels had to close during the lockdown, also our favourite pizzeria “Al Castagno”, so my partner tried really hard to get the perfect pizza dough. This also means that we ate a lot of pizza in the lockdown. I love pizza, but from time to time I want to eat other meals as well.","jb04.jpg"],
    ["Emma 05 Home-Studies","47.25936317749856", "11.389755572632998", "I started my studies in autumn 2019 and was so happy I can start again; my employer agreed to take a year for an educational leave. When the pandemic started in spring 2020, we all were shocked and didn’t know if we can continue our master studies. After a few weeks of chaos, we all tried to reorganize, the students and the lecturers. It was pretty hard to do all our group work on our own, only connected via mobile phones or video conferences. I missed and still miss the exchange with my colleagues and also the joint group work where we all work together in one room. Especially the method courses are much easier when the lecture and the students are in direct contact.","jb05.jpg"],
    ["Emma 06 Our Dog","47.26184099994094", "11.323800215616721", "Our lovely dog was a great help in the first lockdown, as we got the chance to get outside. It was not allowed to go outside, only for very important reasons (grocery shopping helping family members go to the doctors or get your medicine) and to go for a walk with your dog. Our dog was very old and so we could only go for short walks, but it was so helpful to go outside in the fresh air and sunlight. It was a big catastrophe when he died after Easter. Not only did we lose a family member, we had another crisis in the covid-19 pandemic.","jb06.jpg"],
    

];
